In [1]:
!nvidia-smi

Tue May 21 12:18:33 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.23       Driver Version: 511.23       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   51C    P8    12W /  N/A |    703MiB /  6144MiB |     18%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch 
from torch import nn

torch.device('cpu'),torch.cuda.device('cuda'),torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x27ec361b670>)

In [3]:
torch.cuda.device_count()

1

In [8]:
def try_gpu(i=0):
    if torch.cuda.device_count()>=i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpu():
    devices=[
        torch.device(f'cuda:{i}')for i in range(torch.cuda.device_count())
    ]
    return devices if devices else [torch.device('cpu')]
    

In [10]:
try_gpu(),try_gpu(10),try_all_gpu()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [11]:
x=torch.ones(2,3,device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [12]:
Y=torch.rand(2,3,device=try_gpu())

In [13]:
Y

tensor([[0.1490, 0.9498, 0.8430],
        [0.7716, 0.2243, 0.0778]], device='cuda:0')

In [15]:
z=x.cuda(0)
z

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [16]:
x+z

tensor([[2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

In [18]:
net=nn.Sequential(nn.Linear(3,1))
net=net.to(device=try_gpu())

In [25]:
net(x)

tensor([[-0.0652],
        [-0.0652]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [26]:
net[0].weight.data.device

device(type='cuda', index=0)