In [1]:
import torch
from d2l import torch as d2l
def corr2d_multi_int(X,K):
    return sum(d2l.corr2d(x,k) for x,k in zip(X,K))

In [2]:
X=torch.tensor([[[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]],
               [[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]])
K=torch.tensor([[[1.0,2.0],[3.0,4.0]],[[0.0,1.0],[2.0,3.0]]])
K

tensor([[[1., 2.],
         [3., 4.]],

        [[0., 1.],
         [2., 3.]]])

In [3]:
corr2d_multi_int(X,K)

tensor([[ 52.,  68.],
        [100., 116.]])

In [4]:
def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_int(X,k) for k in K],0)

K=torch.stack((K,K+1,K+2),0)
K


tensor([[[[1., 2.],
          [3., 4.]],

         [[0., 1.],
          [2., 3.]]],


        [[[2., 3.],
          [4., 5.]],

         [[1., 2.],
          [3., 4.]]],


        [[[3., 4.],
          [5., 6.]],

         [[2., 3.],
          [4., 5.]]]])

In [5]:
corr2d_multi_in_out(X,K)

tensor([[[ 52.,  68.],
         [100., 116.]],

        [[ 72.,  96.],
         [144., 168.]],

        [[ 92., 124.],
         [188., 220.]]])

1*1的卷积

In [6]:
def corr2d_multi_in_out_1x1(X,K):
    c_i,h,w=X.shape
    c_o=K.shape[0]
    X=X.reshape((c_i,h*w))
    K=K.reshape((c_o,c_i))
    Y=torch.matmul(K,X)
    return Y.reshape((c_o,h,w))

X=torch.normal(0,1,(3,3,3))
K=torch.normal(0,1,(2,3,1,1))

Y1=corr2d_multi_in_out_1x1(X,K)
Y2=corr2d_multi_in_out(X,K)

assert float(torch.abs(Y1-Y2).sum())<1e-6
K

tensor([[[[-1.4783]],

         [[ 0.2696]],

         [[-1.2519]]],


        [[[-0.2477]],

         [[ 0.6742]],

         [[-0.2477]]]])

In [7]:
X.shape

torch.Size([3, 3, 3])

In [8]:
K=torch.normal(0,1,(2,3,1,1))
K=K.reshape((2,3))
K

tensor([[0.0407, 1.0614, 0.7877],
        [0.4444, 1.1959, 0.2070]])

In [9]:
X

tensor([[[ 7.0528e-01, -6.6661e-01,  1.0672e+00],
         [ 7.5870e-01,  6.0122e-01, -7.3786e-01],
         [-1.3015e+00,  1.1065e+00, -7.1500e-01]],

        [[-1.5203e+00,  1.3234e+00,  1.1500e+00],
         [ 4.2013e-01,  7.0590e-01, -3.5055e-01],
         [-1.7595e+00, -8.0103e-01,  2.4193e-02]],

        [[ 2.7468e+00, -1.0438e+00, -8.4316e-01],
         [-1.3740e+00, -2.6963e-01, -2.2793e-03],
         [-1.4213e+00,  6.1028e-02,  1.7543e+00]]])